// Native macOS boundary: translate a validated task authority into a
// deny-default Seatbelt profile for `sandbox-exec`. The profile grants only
// explicit read roots/files, task write roots, private output/scratch, the
// assigned terminal, approved ordinary outbound networking (plus the OS DNS
// socket), and owned local ports. Protected Git metadata, coordinator state,
// policy, and credential sources are denied after the allows.
//
// `sandbox-exec` is deprecated by Apple. Availability is not proof of complete
// containment; required runtime compositions stay unverified until evidenced.

import { type Outcome, refuse, success } from "../contracts/blockers.ts";
import type { ResolvedAuthority } from "../contracts/authority.ts";
import { dedupeRoots, isWithin } from "../contracts/paths.ts";
import { sha256 } from "../util/canonical.ts";

export const PROFILE_TEMPLATE_VERSION = "radian.seatbelt/1";

/** System roots readable by every contained process (toolchains and dynamic loader). */
export const SYSTEM_READ_ROOTS: readonly string[] = ["/System", "/usr", "/bin", "/sbin", "/Library/Apple", "/private/var/db/timezone", "/private/etc/ssl"];
export const SYSTEM_READ_FILES: readonly string[] = ["/", "/private", "/private/tmp", "/dev/null", "/dev/random", "/dev/urandom", "/dev/zero", "/private/etc/hosts", "/private/etc/resolv.conf", "/private/etc/services", "/private/etc/protocols", "/private/etc/localtime"];
export const DNS_SOCKET = "/private/var/run/mDNSResponder";

export interface DependencyAccess {
  /** Directories the runtime/toolchain needs to read (install roots, interpreters). */
  readRoots: readonly string[];
  /** Individual files (resolved dynamic libraries, certificates). */
  readFiles: readonly string[];
}

export interface ProfileInput {
  authority: ResolvedAuthority;
  dependencies: DependencyAccess;
  /** Read-only credential projection directory, if one is exposed. */
  credentialDir?: string;
  /** Additional paths that must never be readable (personal credential stores). */
  denyRead?: readonly string[];
  /** Assigned terminal device (e.g. /dev/ttys004); filled in by the launcher. */
  terminal?: string;
  /** Worktree Git pointer file, which workers must not rewrite. */
  gitPointer?: string;
}

export interface GeneratedProfile {
  text: string;
  hash: string;
  template: string;
}

const SAFE_PATH = /^\/[A-Za-z0-9 ._@+,=:~\/-]*$/;
export const TERMINAL_PATTERN = /^\/dev\/ttys[0-9]{3,4}$/;

function q(path: string): string {
  return `"${path}"`;
}

function checkPaths(paths: readonly string[]): Outcome<true> {
  for (const p of paths) {
    if (!SAFE_PATH.test(p) || p.includes("//") || p.split("/").includes("..")) {
      return refuse("PATH_INVALID", "a profile path contains characters that cannot be expressed safely");
    }
  }
  return success(true);
}

export function generateProfile(input: ProfileInput): Outcome<GeneratedProfile> {
  const a = input.authority;
  const readRoots = dedupeRoots([...SYSTEM_READ_ROOTS, ...a.readRoots, ...input.dependencies.readRoots, a.outputDir, a.scratchDir, ...(input.credentialDir ? [input.credentialDir] : [])]);
  const readFiles = [...new Set([...SYSTEM_READ_FILES, ...input.dependencies.readFiles])].sort();
  const writeRoots = dedupeRoots([...a.writeRoots, a.outputDir, a.scratchDir]);
  const denyWrite = dedupeRoots([...a.protectedPaths, ...(input.credentialDir ? [input.credentialDir] : [])]);
  const denyRead = dedupeRoots([...(input.denyRead ?? [])]);
  const all = [...readRoots, ...readFiles, ...writeRoots, ...denyWrite, ...denyRead, ...(input.gitPointer ? [input.gitPointer] : [])];
  const checked = checkPaths(all);
  if (!checked.ok) return checked;
  if (input.terminal !== undefined && !TERMINAL_PATTERN.test(input.terminal)) return refuse("PATH_INVALID", "terminal must be a specific /dev/ttysNNN device");
  for (const root of writeRoots) {
    if (denyWrite.some((guarded) => isWithin(root, guarded))) return refuse("POLICY_TAMPERED", "a writable root lies inside a protected path");
  }
  for (const root of [...readRoots, ...writeRoots]) {
    if (denyRead.some((guarded) => isWithin(root, guarded))) return refuse("POLICY_TAMPERED", "a granted root lies inside a denied credential path");
  }

  const lines: string[] = [
    "(version 1)",
    `; ${PROFILE_TEMPLATE_VERSION} generated by Radian; do not edit`,
    "(deny default)",
    "(allow process-exec)",
    "(allow process-fork)",
    "(allow sysctl-read)",
    // Path metadata (names, sizes) is traversable; file contents are not.
    "(allow file-read-metadata)",
    "(allow signal (target same-sandbox))",
  ];
  lines.push(`(allow file-read* ${readFiles.map((f) => `(literal ${q(f)})`).join(" ")})`);
  for (const root of readRoots) lines.push(`(allow file-read* (subpath ${q(root)}))`);
  lines.push(`(allow file-write* (literal "/dev/null"))`);
  for (const root of writeRoots) lines.push(`(allow file-write* (subpath ${q(root)}))`);
  if (input.terminal) {
    lines.push(`(allow file-read* file-write* file-ioctl (literal ${q(input.terminal)}))`);
  }
  // Approved ordinary outbound networking; no destination isolation is claimed.
  lines.push(`(allow network-outbound (remote ip "*:*"))`);
  lines.push(`(allow network-outbound (remote unix-socket (literal ${q(DNS_SOCKET)})))`);
  for (const port of a.ports) {
    lines.push(`(allow network-bind (local ip "localhost:${port}"))`);
    lines.push(`(allow network-inbound (local ip "localhost:${port}"))`);
  }
  // Later rules take precedence: protected state and credentials are denied last.
  for (const root of denyWrite) lines.push(`(deny file-write* (subpath ${q(root)}))`);
  if (input.gitPointer) lines.push(`(deny file-write* (literal ${q(input.gitPointer)}))`);
  for (const root of denyRead) lines.push(`(deny file-read* file-write* (subpath ${q(root)}))`);
  const text = lines.join("\n") + "\n";
  return success({ text, hash: "sha256:" + sha256(text), template: PROFILE_TEMPLATE_VERSION });
}

export type AccessMode = "read" | "write";

export interface AccessDiagnosis {
  allowed: boolean;
  /** Stable rule ID for denial diagnostics. */
  rule: "RH-ALLOW-WRITE-ROOT" | "RH-ALLOW-READ-ROOT" | "RH-DENY-PROTECTED" | "RH-DENY-CREDENTIAL" | "RH-DENY-GIT-POINTER" | "RH-DENY-OUTSIDE-SCOPE";
  reason: string;
  alternative?: string;
}

/**
 * Explain how the generated profile treats a canonical path, for safe denied-
 * action diagnostics. Mirrors the rule order of generateProfile (denies last).
 */
export function diagnoseAccess(input: ProfileInput, canonical: string, mode: AccessMode): AccessDiagnosis {
  const a = input.authority;
  if ((input.denyRead ?? []).some((root) => isWithin(canonical, root))) {
    return { allowed: false, rule: "RH-DENY-CREDENTIAL", reason: "personal credential stores are never readable by workers", alternative: "Use the projected subscription credential provided for this assignment." };
  }
  if (mode === "write") {
    if (input.gitPointer && canonical === input.gitPointer) return { allowed: false, rule: "RH-DENY-GIT-POINTER", reason: "the worktree Git pointer is coordinator-owned" };
    if ([...a.protectedPaths, ...(input.credentialDir ? [input.credentialDir] : [])].some((root) => isWithin(canonical, root))) {
      return { allowed: false, rule: "RH-DENY-PROTECTED", reason: "shared Git metadata, coordinator state, policy, and credential projections are protected", alternative: "Deliver file changes; Radian creates commits and records state." };
    }
    if ([...a.writeRoots, a.outputDir, a.scratchDir].some((root) => isWithin(canonical, root))) return { allowed: true, rule: "RH-ALLOW-WRITE-ROOT", reason: "inside a task write root" };
    return { allowed: false, rule: "RH-DENY-OUTSIDE-SCOPE", reason: "outside the assignment's write scope", alternative: "Ask the coordinator for a scope decision." };
  }
  const readable = [...SYSTEM_READ_ROOTS, ...a.readRoots, ...input.dependencies.readRoots, a.outputDir, a.scratchDir, ...(input.credentialDir ? [input.credentialDir] : [])];
  if (readable.some((root) => isWithin(canonical, root)) || input.dependencies.readFiles.includes(canonical) || SYSTEM_READ_FILES.includes(canonical)) {
    return { allowed: true, rule: "RH-ALLOW-READ-ROOT", reason: "inside a permitted read root" };
  }
  return { allowed: false, rule: "RH-DENY-OUTSIDE-SCOPE", reason: "outside the assignment's read scope", alternative: "Ask the coordinator to add the source to the task's read scope." };
}
